--
-- PostgreSQL database dump
--

\restrict GnQHuRdUlpT3CVcydmNsx49LJctKXWo5emrrePQKfF65HCzKtf80QYqfJTl2QLA

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: assets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assets (
    id bigint NOT NULL,
    asset_key text NOT NULL,
    asset_type character varying(30) NOT NULL,
    display_order integer,
    CONSTRAINT assets_asset_type_check CHECK (((asset_type)::text = ANY ((ARRAY['BACKGROUND'::character varying, 'STICKER'::character varying, 'GIFT_STICKER'::character varying, 'ROLLING_PAPER_PROFILE'::character varying])::text[])))
);


--
-- Name: assets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.assets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: board_assets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.board_assets (
    id bigint NOT NULL,
    asset_key text NOT NULL,
    asset_type character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    slot_index integer,
    board_id bigint NOT NULL,
    CONSTRAINT board_assets_asset_type_check CHECK (((asset_type)::text = ANY ((ARRAY['BACKGROUND'::character varying, 'STICKER'::character varying, 'GIFT_STICKER'::character varying])::text[])))
);


--
-- Name: board_assets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.board_assets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.board_assets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


--
-- Name: notice_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notice_images (
    id bigint NOT NULL,
    notice_id bigint NOT NULL,
    image_url character varying(500) NOT NULL,
    display_order integer NOT NULL
);


--
-- Name: notice_images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.notice_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: notice_images_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.notice_images_id_seq OWNED BY public.notice_images.id;


--
-- Name: notices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notices (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    banner_text character varying(255),
    is_pinned boolean DEFAULT false NOT NULL,
    start_at timestamp without time zone NOT NULL,
    end_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: notices_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.notices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: notices_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.notices_id_seq OWNED BY public.notices.id;


--
-- Name: rolling_paper_comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rolling_paper_comments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    rolling_paper_id bigint,
    user_id bigint,
    is_user boolean DEFAULT true NOT NULL,
    sender_name character varying(8) NOT NULL,
    content text NOT NULL,
    sticker_key text,
    slot_index integer,
    guest_password character varying(255)
);


--
-- Name: rolling_paper_comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rolling_paper_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rolling_paper_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rolling_papers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rolling_papers (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint,
    slug character varying(100) NOT NULL,
    title character varying(12) NOT NULL,
    recipient_name character varying(100),
    image_key text,
    target_date date NOT NULL,
    comment_token character varying(100),
    view_token character varying(100),
    is_saved_copy boolean DEFAULT false NOT NULL,
    saved_by_user_id bigint,
    save_source character varying(20),
    deleted_at timestamp without time zone,
    is_comment_public boolean DEFAULT false NOT NULL,
    CONSTRAINT rolling_papers_save_source_check CHECK (((save_source)::text = ANY ((ARRAY['CREATED'::character varying, 'RECEIVED'::character varying])::text[])))
);


--
-- Name: rolling_papers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rolling_papers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rolling_papers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: share_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.share_links (
    id bigint NOT NULL,
    short_code character varying(20) NOT NULL,
    original_url character varying(2048) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: share_links_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.share_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: share_links_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.share_links_id_seq OWNED BY public.share_links.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(100),
    gender character varying(10),
    grade character varying(20),
    nickname character varying(50),
    password_hash character varying(255) NOT NULL,
    provider character varying(20) NOT NULL,
    provider_id character varying(100),
    role character varying(20) NOT NULL,
    school character varying(100),
    school_code character varying(100),
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    username character varying(50) NOT NULL,
    team_tag character varying(50) DEFAULT NULL::character varying,
    CONSTRAINT users_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT users_provider_check CHECK (((provider)::text = ANY ((ARRAY['LOCAL'::character varying, 'KAKAO'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY (ARRAY[('CHILD'::character varying)::text, ('PARENT'::character varying)::text, ('ADMIN'::character varying)::text, ('TEAM'::character varying)::text]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'BANNED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wish_boards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wish_boards (
    id bigint NOT NULL,
    board_slug character varying(100) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_public boolean NOT NULL,
    target_date date,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    title character varying(12),
    is_saved_copy boolean DEFAULT false NOT NULL,
    saved_by_user_id bigint,
    deleted_at timestamp without time zone,
    is_comment_public boolean DEFAULT false NOT NULL
);


--
-- Name: wish_boards_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wish_boards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wish_boards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wish_comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wish_comments (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_user boolean NOT NULL,
    sender_name character varying(8) NOT NULL,
    sticker_key text NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint,
    wish_list_id bigint,
    slot_index integer,
    guest_password character varying(255)
);


--
-- Name: wish_comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wish_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wish_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wish_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wish_items (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    item_name character varying(100),
    like_count integer NOT NULL,
    slot_index integer NOT NULL,
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    board_id bigint NOT NULL,
    CONSTRAINT wish_items_status_check CHECK (((status)::text = ANY ((ARRAY['WANTED'::character varying, 'RECEIVED'::character varying, 'CANCELED'::character varying])::text[])))
);


--
-- Name: wish_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wish_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wish_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notice_images id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notice_images ALTER COLUMN id SET DEFAULT nextval('public.notice_images_id_seq'::regclass);


--
-- Name: notices id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notices ALTER COLUMN id SET DEFAULT nextval('public.notices_id_seq'::regclass);


--
-- Name: share_links id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.share_links ALTER COLUMN id SET DEFAULT nextval('public.share_links_id_seq'::regclass);


--
-- Name: assets assets_asset_key_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_asset_key_unique UNIQUE (asset_key);


--
-- Name: assets assets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_pkey PRIMARY KEY (id);


--
-- Name: board_assets board_assets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_assets
    ADD CONSTRAINT board_assets_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: notice_images notice_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notice_images
    ADD CONSTRAINT notice_images_pkey PRIMARY KEY (id);


--
-- Name: notices notices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notices
    ADD CONSTRAINT notices_pkey PRIMARY KEY (id);


--
-- Name: rolling_paper_comments rolling_paper_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rolling_paper_comments
    ADD CONSTRAINT rolling_paper_comments_pkey PRIMARY KEY (id);


--
-- Name: rolling_papers rolling_papers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rolling_papers
    ADD CONSTRAINT rolling_papers_pkey PRIMARY KEY (id);


--
-- Name: share_links share_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.share_links
    ADD CONSTRAINT share_links_pkey PRIMARY KEY (id);


--
-- Name: share_links share_links_short_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.share_links
    ADD CONSTRAINT share_links_short_code_key UNIQUE (short_code);


--
-- Name: wish_boards uk290fan6b8b7t8oftui0b5d8ar; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wish_boards
    ADD CONSTRAINT uk290fan6b8b7t8oftui0b5d8ar UNIQUE (board_slug);


--
-- Name: users uk2ty1xmrrgtn89xt7kyxx6ta7h; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk2ty1xmrrgtn89xt7kyxx6ta7h UNIQUE (nickname);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: rolling_papers uk_rolling_papers_comment_token; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rolling_papers
    ADD CONSTRAINT uk_rolling_papers_comment_token UNIQUE (comment_token);


--
-- Name: rolling_papers uk_rolling_papers_slug; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rolling_papers
    ADD CONSTRAINT uk_rolling_papers_slug UNIQUE (slug);


--
-- Name: rolling_papers uk_rolling_papers_view_token; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rolling_papers
    ADD CONSTRAINT uk_rolling_papers_view_token UNIQUE (view_token);


--
-- Name: wish_comments uk_wish_comments_board_slot; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wish_comments
    ADD CONSTRAINT uk_wish_comments_board_slot UNIQUE (wish_list_id, slot_index);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: rolling_paper_comments uq_rp_comments_paper_slot; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rolling_paper_comments
    ADD CONSTRAINT uq_rp_comments_paper_slot UNIQUE (rolling_paper_id, slot_index);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: wish_boards wish_boards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wish_boards
    ADD CONSTRAINT wish_boards_pkey PRIMARY KEY (id);


--
-- Name: wish_comments wish_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wish_comments
    ADD CONSTRAINT wish_comments_pkey PRIMARY KEY (id);


--
-- Name: wish_items wish_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wish_items
    ADD CONSTRAINT wish_items_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: idx_rolling_papers_saved_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rolling_papers_saved_by ON public.rolling_papers USING btree (saved_by_user_id);


--
-- Name: idx_rolling_papers_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rolling_papers_user_id ON public.rolling_papers USING btree (user_id);


--
-- Name: idx_rp_comments_rolling_paper_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_rp_comments_rolling_paper_id ON public.rolling_paper_comments USING btree (rolling_paper_id);


--
-- Name: idx_share_links_short_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_share_links_short_code ON public.share_links USING btree (short_code);


--
-- Name: idx_wish_boards_saved_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_wish_boards_saved_by ON public.wish_boards USING btree (saved_by_user_id);


--
-- Name: wish_items fk8hn23pfygysrk8vf0l2aep0hb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wish_items
    ADD CONSTRAINT fk8hn23pfygysrk8vf0l2aep0hb FOREIGN KEY (board_id) REFERENCES public.wish_boards(id);


--
-- Name: rolling_papers fk_rolling_papers_saved_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rolling_papers
    ADD CONSTRAINT fk_rolling_papers_saved_by FOREIGN KEY (saved_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: rolling_papers fk_rolling_papers_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rolling_papers
    ADD CONSTRAINT fk_rolling_papers_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: rolling_paper_comments fk_rp_comments_rolling_paper; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rolling_paper_comments
    ADD CONSTRAINT fk_rp_comments_rolling_paper FOREIGN KEY (rolling_paper_id) REFERENCES public.rolling_papers(id) ON DELETE SET NULL;


--
-- Name: rolling_paper_comments fk_rp_comments_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rolling_paper_comments
    ADD CONSTRAINT fk_rp_comments_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: wish_boards fk_wish_boards_saved_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wish_boards
    ADD CONSTRAINT fk_wish_boards_saved_by FOREIGN KEY (saved_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: wish_comments fk_wish_comments_wish_board; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wish_comments
    ADD CONSTRAINT fk_wish_comments_wish_board FOREIGN KEY (wish_list_id) REFERENCES public.wish_boards(id) ON DELETE SET NULL;


--
-- Name: board_assets fkccf392jy48cgnaftio8m0x752; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_assets
    ADD CONSTRAINT fkccf392jy48cgnaftio8m0x752 FOREIGN KEY (board_id) REFERENCES public.wish_boards(id);


--
-- Name: wish_comments fkfh7t3fvo0vnora3iktby0yywl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wish_comments
    ADD CONSTRAINT fkfh7t3fvo0vnora3iktby0yywl FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: wish_boards fkoo5beaj7ctsofndy88i53tsa3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wish_boards
    ADD CONSTRAINT fkoo5beaj7ctsofndy88i53tsa3 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: notice_images notice_images_notice_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notice_images
    ADD CONSTRAINT notice_images_notice_id_fkey FOREIGN KEY (notice_id) REFERENCES public.notices(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict GnQHuRdUlpT3CVcydmNsx49LJctKXWo5emrrePQKfF65HCzKtf80QYqfJTl2QLA

