-- V13: 롤링페이퍼 및 롤링페이퍼 댓글 테이블 신규 생성
-- 비로그인 댓글 지원, 공개일 기반 댓글 마스킹, 독립 복사본 저장 기능 포함

-- 1. rolling_papers 테이블 생성
CREATE TABLE IF NOT EXISTS rolling_papers (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMP(6)  NOT NULL,
    updated_at       TIMESTAMP(6)  NOT NULL,
    user_id          BIGINT        NOT NULL,                        -- 생성자 FK
    slug             VARCHAR(100)  NOT NULL,                        -- 공개 URL 슬러그
    title            VARCHAR(200)  NOT NULL,                        -- 롤링페이퍼 제목
    recipient_name   VARCHAR(100)  NOT NULL,                        -- 받는 사람 이름
    image_key        TEXT,                                          -- 받는 사람 이미지 CDN 키 (선택)
    target_date      DATE          NOT NULL,                        -- 댓글 공개 기준일
    comment_token    VARCHAR(100),                                  -- 댓글 작성용 공유 링크 토큰 (원본만 발급, 복사본은 NULL)
    view_token       VARCHAR(100),                                  -- 저장 전용 공유 링크 토큰 (원본만 발급, 복사본은 NULL)
    is_saved_copy    BOOLEAN       NOT NULL DEFAULT FALSE,          -- true = 저장된 독립 복사본 / false = 원본
    saved_by_user_id BIGINT,                                        -- 복사본을 저장한 사용자 (원본이면 NULL)
    save_source      VARCHAR(20),                                   -- CREATED(생성자 저장) / RECEIVED(수신자 저장) / NULL(원본)
    deleted_at       TIMESTAMP,                                     -- 스케줄러에 의한 soft delete 일시 (NULL = 유효한 원본)

    CONSTRAINT uk_rolling_papers_slug
        UNIQUE (slug),
    CONSTRAINT uk_rolling_papers_comment_token
        UNIQUE (comment_token),
    CONSTRAINT uk_rolling_papers_view_token
        UNIQUE (view_token),
    CONSTRAINT fk_rolling_papers_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE,                                          -- 회원 탈퇴 시 롤링페이퍼 전체 삭제
    CONSTRAINT fk_rolling_papers_saved_by
        FOREIGN KEY (saved_by_user_id) REFERENCES users (id)
        ON DELETE SET NULL,                                         -- 저장한 사람이 탈퇴해도 복사본 데이터는 유지
    CONSTRAINT rolling_papers_save_source_check
        CHECK (save_source IN ('CREATED', 'RECEIVED'))
);

-- 2. rolling_paper_comments 테이블 생성 (비회원 작성 가능)
CREATE TABLE IF NOT EXISTS rolling_paper_comments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMP(6) NOT NULL,
    updated_at       TIMESTAMP(6) NOT NULL,
    rolling_paper_id BIGINT       NOT NULL,                        -- 소속 롤링페이퍼 FK
    user_id          BIGINT,                                        -- 작성자 FK (비회원이면 NULL)
    is_user          BOOLEAN      NOT NULL DEFAULT TRUE,            -- true = 회원 댓글 / false = 비회원 댓글
    sender_name      VARCHAR(8)   NOT NULL,                        -- 작성 시점 닉네임 스냅샷
    content          TEXT         NOT NULL,                        -- 댓글 본문
    sticker_key      TEXT,                                          -- 스티커 CDN 키 (선택)
    slot_index       INTEGER,                                       -- 댓글 슬롯 위치 (선택)
    guest_password   VARCHAR(255),                                  -- 비회원 댓글 수정·삭제용 해시 비밀번호 (회원이면 NULL)

    CONSTRAINT fk_rp_comments_rolling_paper
        FOREIGN KEY (rolling_paper_id) REFERENCES rolling_papers (id)
        ON DELETE CASCADE,                                          -- 롤링페이퍼 삭제 시 댓글도 삭제
    CONSTRAINT fk_rp_comments_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE SET NULL,                                         -- 작성자 탈퇴 시 댓글 익명 처리 (내용 유지)
    CONSTRAINT uq_rp_comments_paper_slot
        UNIQUE (rolling_paper_id, slot_index)                       -- 동일 롤링페이퍼 내 슬롯 번호 중복 불가
);

-- 3. 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_rolling_papers_user_id       ON rolling_papers          (user_id);           -- 내 롤링페이퍼 목록 조회 최적화
CREATE INDEX IF NOT EXISTS idx_rolling_papers_saved_by      ON rolling_papers          (saved_by_user_id);  -- 내가 저장한 롤링페이퍼 목록 조회 최적화
CREATE INDEX IF NOT EXISTS idx_rp_comments_rolling_paper_id ON rolling_paper_comments  (rolling_paper_id);  -- 롤링페이퍼별 댓글 조회 최적화
