-- V1: 전체 스키마 초기 생성
-- 기존 DB에서는 baseline-on-migrate=true 설정으로 인해 이 파일은 건너뜁니다.
-- 새 PC에서 처음 실행할 때만 실행됩니다.

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    email         VARCHAR(100),
    gender        VARCHAR(10),
    grade         VARCHAR(20),
    nickname      VARCHAR(50)  NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    provider      VARCHAR(20)  NOT NULL,
    provider_id   VARCHAR(100),
    role          VARCHAR(20)  NOT NULL,
    school        VARCHAR(100),
    school_code   VARCHAR(100),
    status        VARCHAR(20)  NOT NULL,
    username      VARCHAR(50)  NOT NULL,
    CONSTRAINT uk2ty1xmrrgtn89xt7kyxx6ta7h UNIQUE (nickname),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
    CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username),
    CONSTRAINT users_gender_check   CHECK (gender   IN ('MALE', 'FEMALE', 'OTHER')),
    CONSTRAINT users_provider_check CHECK (provider IN ('LOCAL', 'KAKAO')),
    CONSTRAINT users_role_check     CHECK (role     IN ('CHILD', 'PARENT', 'ADMIN')),
    CONSTRAINT users_status_check   CHECK (status   IN ('ACTIVE', 'INACTIVE', 'BANNED', 'DELETED'))
);

CREATE TABLE IF NOT EXISTS wish_boards (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(6)  NOT NULL,
    updated_at  TIMESTAMP(6)  NOT NULL,
    board_slug  VARCHAR(100)  NOT NULL,
    is_public   BOOLEAN       NOT NULL,
    target_date DATE,
    user_id     BIGINT        NOT NULL,
    CONSTRAINT uk290fan6b8b7t8oftui0b5d8ar UNIQUE (board_slug),
    CONSTRAINT ukcp3g7txu69h866ksqj7qcjyu4 UNIQUE (user_id),
    CONSTRAINT fkoo5beaj7ctsofndy88i53tsa3 FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS wish_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    item_name   VARCHAR(100),
    like_count  INTEGER      NOT NULL,
    slot_index  INTEGER      NOT NULL,
    status      VARCHAR(20)  NOT NULL,
    board_id    BIGINT       NOT NULL,
    CONSTRAINT wish_items_status_check CHECK (status IN ('WANTED', 'RECEIVED', 'CANCELED')),
    CONSTRAINT fk8hn23pfygysrk8vf0l2aep0hb FOREIGN KEY (board_id) REFERENCES wish_boards (id)
);

CREATE TABLE IF NOT EXISTS assets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_key     TEXT        NOT NULL,
    asset_type    VARCHAR(20) NOT NULL,
    display_order INTEGER,
    CONSTRAINT assets_asset_type_check CHECK (asset_type IN ('BACKGROUND', 'STICKER', 'GIFT_STICKER'))
);

CREATE TABLE IF NOT EXISTS board_assets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_key   TEXT        NOT NULL,
    asset_type  VARCHAR(20) NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    slot_index  INTEGER,
    board_id    BIGINT      NOT NULL,
    CONSTRAINT board_assets_asset_type_check CHECK (asset_type IN ('BACKGROUND', 'STICKER', 'GIFT_STICKER')),
    CONSTRAINT fkccf392jy48cgnaftio8m0x752 FOREIGN KEY (board_id) REFERENCES wish_boards (id)
);

CREATE TABLE IF NOT EXISTS wish_comments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content      TEXT        NOT NULL,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    is_user      BOOLEAN     NOT NULL,
    sender_name  VARCHAR(8)  NOT NULL,
    sticker_key  TEXT        NOT NULL,
    user_id      BIGINT,
    wish_list_id BIGINT      NOT NULL,
    CONSTRAINT fkfh7t3fvo0vnora3iktby0yywl FOREIGN KEY (user_id)      REFERENCES users (id),
    CONSTRAINT fkfv2x787r3u0j1goigtbhqdl2w FOREIGN KEY (wish_list_id) REFERENCES wish_boards (id)
);
