services:
  postgres:
    image: postgres:16
    container_name: oh-jjeom-oh-postgres
    environment:
      POSTGRES_DB: oh_jjeom_oh
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/docker/volumes/2464f3d841fd3164a34ea991c1b861da8a746a4e1f49e59dbc333ae49866d009/_data:/var/lib/postgresql/data
    networks:
      - oh-jjeom-oh-net

  redis:
    image: redis:7
    container_name: oh-jjeom-oh-redis
    ports:
      - "6379:6379"
    networks:
      - oh-jjeom-oh-net

  backend:
    image: ghcr.io/${GHCR_USER}/server-image:${SERVER_IMAGE_TAG:-latest}
    container_name: backend-server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN2_USERNAME=${ADMIN2_USERNAME} 
      - ADMIN2_PASSWORD=${ADMIN2_PASSWORD} 
      - GMS_KEY=${GMS_KEY}
      - DB_URL=jdbc:postgresql://oh-jjeom-oh-postgres:5432/oh_jjeom_oh
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=oh-jjeom-oh-redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION:-ap-northeast-2}
      - S3_BUCKET=${S3_BUCKET:-five-dot-five}
    networks:
      - oh-jjeom-oh-net
  
  # 신규 서버 1번
  backend-blue:
    image: ghcr.io/${GHCR_USER}/server-image:${SERVER_IMAGE_TAG:-latest}
    container_name: backend-blue
    ports:
      - "8081:8080" # 외부에서 8081로 접속하면 컨테이너 안의 8080으로 연결.
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN2_USERNAME=${ADMIN2_USERNAME} 
      - ADMIN2_PASSWORD=${ADMIN2_PASSWORD} 
      - DB_URL=jdbc:postgresql://oh-jjeom-oh-postgres:5432/oh_jjeom_oh
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - GMS_KEY=${GMS_KEY}
      - REDIS_HOST=oh-jjeom-oh-redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION:-ap-northeast-2}
      - S3_BUCKET=${S3_BUCKET:-five-dot-five}
    networks:
      - oh-jjeom-oh-net
    restart: always

  # 신규 서버 2번
  backend-green:
    image: ghcr.io/${GHCR_USER}/server-image:${SERVER_IMAGE_TAG:-latest}
    container_name: backend-green
    ports:
      - "8082:8080" # 외부에서 8082로 접속하면 컨테이너 안의 8080으로 연결
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN2_USERNAME=${ADMIN2_USERNAME} 
      - ADMIN2_PASSWORD=${ADMIN2_PASSWORD} 
      - DB_URL=jdbc:postgresql://oh-jjeom-oh-postgres:5432/oh_jjeom_oh
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - GMS_KEY=${GMS_KEY}
      - REDIS_HOST=oh-jjeom-oh-redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION:-ap-northeast-2}
      - S3_BUCKET=${S3_BUCKET:-five-dot-five}
    networks:
      - oh-jjeom-oh-net
    restart: always

  client:
    image: ghcr.io/${GHCR_USER}/client-image:${CLIENT_IMAGE_TAG:-latest}
    container_name: nextjs-client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_NGROK_URL=${NEXT_PUBLIC_NGROK_URL}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
      - NEXT_PUBLIC_IMAGE_REMOTE_HOSTS=${NEXT_PUBLIC_IMAGE_REMOTE_HOSTS}
      - NEXT_PUBLIC_ASSET_BASE_URL=${NEXT_PUBLIC_ASSET_BASE_URL}
    networks:
      - oh-jjeom-oh-net
    restart: always

networks:
  oh-jjeom-oh-net:
    driver: bridge

volumes:
  postgres_data: