services:
  postgres:
    image: postgres:16
    container_name: oh-jjeom-oh-postgres
    environment:
      POSTGRES_DB: oh_jjeom_oh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - oh-jjeom-oh-net

  redis:
    image: redis:7
    container_name: oh-jjeom-oh-redis
    ports:
      - "6379:6379"
    networks:
      - oh-jjeom-oh-net

  backend:
    image: ghcr.io/${GHCR_USER}/server-image:latest
    container_name: backend-server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
    networks:
      - oh-jjeom-oh-net

  client:
    image: ghcr.io/${GHCR_USER}/client-image:latest
    container_name: nextjs-client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://k14f205.p.ssafy.io/api
    networks:
      - oh-jjeom-oh-net
    restart: always

networks:
  oh-jjeom-oh-net:
    driver: bridge

volumes:
  postgres_data: